### ISSUE TITLE
Is there a way of uploading dictionaries using API?

### ISSUE THREAD

**Issue by nabinkhadka** [tagtog/tagtog-doc#14]
Is there any endpoint for uploading dictionaries in TSV format which can be accomplished as these below?

<img width="612" alt="Screen Shot 2020-04-29 at 18 41 51" src="https://user-images.githubusercontent.com/6050613/80598541-413d3f00-8a49-11ea-942d-f2f2c2d31429.png">
<img width="1010" alt="Screen Shot 2020-04-29 at 18 41 59" src="https://user-images.githubusercontent.com/6050613/80598550-469a8980-8a49-11ea-8c3b-873c57e29510.png">

**Comment by juanmirocks** [comment]
Dear @nabinkhadka 

great day to you!

I'm very sorry you didn't hear an answer from us before. We are better reachable at our [email address](https://tagtog.net/#contact).

Answering your question, no, at the moment we do not have an official API for this. Having said that, we do have plans to release such an API. I got your email address from your exquisite command-line-like website, and we will notify you as soon as the feature is ready.

For anything else, we are gladly available via email.

**Comment by nabinkhadka** [comment]
No worries. Glad you found me :)
