### ISSUE TITLE
Allow passing of CA_BUNDLE to ssl_verify param in tagtog.py

### ISSUE THREAD

**Issue by clgarciga** [tagtog/tagtog-doc#17]
In `tagtog.py` , change: 

`parser.add_argument("--verify_ssl", type=str2bool, default=True, help="(Optional) Choose to verify or not the ssl certificate of the endpoint domain when making http requests; true by default")`

to take `TRUE`, `FALSE`, or a path to a CA_BUNDLE file or directory with certificates of trusted CAs for use in `requests.get`, for example:

`requests.get('https://github.com', verify='/path/to/certfile')`

**Comment by juanmirocks** [comment]
Thanks @clgarciga 

This definitely makes sense. We will track this improvement and let you know.

**Comment by clgarciga** [comment]
Thank you!

**Comment by juanmirocks** [comment]
@clgarciga improvement already available on our master branch 👍

**Comment by clgarciga** [comment]
Thank you!
