### ISSUE TITLE
[ProtoProteinSearch user story] Disease target based search

### ISSUE THREAD

**Issue by sacdallago** [tagtog/tagtog-doc#3]
A user should be able to input:

> protein(s) [targeted | attacked | involved |...] by acetylsalicylic acid 

and get a result of the from

```json
{
  "queryType": "drugTarget",
  "result": [
    {
      "uniprot": "ABCD123",
      "confidence": 0.7
    }, {
      "uniprot": "ABCD124"
    }
  ]
}
```

**Comment by sacdallago** [comment]
I can provide this data! Taken from https://www.drugbank.ca

**Comment by juanmirocks** [comment]
Thanks @sacdallago ! This is a great proposal.

We have to review internally if we want to have all PubMed constantly indexed. Ofc ideally yes, but we are putting now also some more focus onto other domains (other than medicine), so we have to balance our efforts. I will let you know asap when I have more information. Thank you!

**Comment by juanmirocks** [comment]
Closing as we are not ready to move with this for now.
