### ISSUE TITLE
Option to delete all regex annotated strings is missing

### ISSUE THREAD

**Issue by resigo** [tagtog/tagtog-doc#32]
Hi,
during annotation of Native PDF documents we have realised that there is no option to delete an annotated entity with all of the occurrences that correspond to it. 

_Example:_ if the annotator wrongly annotates a word, the regex annotation will immediately find all the words in the text which may result in tens or hundreds of words being selected and highlighted. If he wants to then remove this wrong entry, he can only delete the specific occurrence of the entity and the rest remains highlighted. Even in the "Entities" sidebar there is no option to bulk delete all of the annotations for a specific term at once.

Please, what is the best practice for annotators to solve this issue? Is there a plan to add "Delete All" button into the menu when you click on the highlighted annotation? 

Thank you.

**Comment by juanmirocks** [comment]
Thanks for writing @resigo !

You can enable & use [pre-deselections](https://docs.tagtog.net/webeditor.html#pre-selections) to remove those wrong automatic annotations.

Please let us know if you have questions.

**Comment by appelts-els** [comment]
Thanks for sharing, this helps and solves the issue.
