### ISSUE TITLE
Computing the filename by sub-stringing the value in Content-Disposition results in broken filenames

### ISSUE THREAD

**Issue by aplz** [tagtog/tagtog-doc#33]
https://github.com/tagtog/tagtog-doc/blob/4e87ebcbabc19c7195cb39103cc431246658e4a9/tagtog.py#L303

I am using the tagtog.py script for downloading data from a private project (we have an On-premises Team plan).

`python tagtog.py download 'folder:pool'  --domain https://localhost:8443 --user <me> --project <project> -w <password> --verify_ssl False --output orig --output_folder <mydir>` 

The responses all look like the example below:
```
{'Server': 'nginx', 'Date': 'Wed, 19 Jan 2022 10:59:40 GMT', 
'Content-Type': 'application/octet-stream', 'Content-Length': '1228', 
'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Request-Time': '3', 
'Content-Encoding': 'gzip', 
'Content-Disposition': 'inline; filename="a.qMG9WVGlFtV9f5JOR64JTxQ.ei-20680818"; filename*=utf-8\'\'a.qMG9WVGlFtV9f5JOR64JTxQ.ei-20680818'}
```
Now using `filename = content_disposition[10:-1]` to compute the output file name results in unusable file names, e.g. here 
`lename="a.qMG9WVGlFtV9f5JOR64JTxQ.ei-20680818"; filename*=utf-8''a.qMG9WVGlFtV9f5JOR64JTxQ.ei-2068081`

**Comment by ashish-narwal** [comment]
Thank you for reporting this. The bug is understood and we will work on fixing it.
